Feature branch
emmanuellekamwa/newsweek pull request #3
Opened 2020-08-07 07:28 UTC by emmanuellekamwa

Hi everyone. I have done most of the work so far and I have tried my best to make the page look as similar as the original even though I know there are still some small issues that I don't really know how to fix them and I want to plead on the TSE that will review the project to give me some tips on how to resolve them. Thanks.

2020-08-07 09:40 UTC, kitpao requested changes
# 👋 Hello @emmanuellekamwa 

🌟 First of all, congratulations on making your page very similar to the original 👏  you did a great job with most of the details 🏅 You put your effort into the project and it shows ✔️ ✔️ ✔️ 

There are some required changes, the visual observations will be in here, and you can find code-related issues in the inline comments at the end ⬇️ ⬇️ 

**_Note 1:_** Since Newsweek page changes a lot, to be fair, I'm using the original page at the date you put in the navbar (July 31) [link here](https://web.archive.org/web/20200731111040/https://www.newsweek.com/)

**_Note 2:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

**_Note 3:_** If you have any trouble implementing the requested changes, you can ask me via text in slack or appoint a zoom meeting with a full-time TSE [here](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-)

- [ ] **[OPTIONAL]** Your images look blurred when they are in mobile, to avoid this, I would recommend you to grab the image URLs from the original site when they are in their biggest size.

### All sizes:
- [ ] Notice that the navbar is fixed, you are missing the labels here, and the 'vs' divider. Please fix it:
![image](https://user-images.githubusercontent.com/53256139/89630163-94066e00-d864-11ea-8f05-024c552ba84f.png)
![image](https://user-images.githubusercontent.com/53256139/89630493-1727c400-d865-11ea-9445-77e6f3f8d769.png)

### Mobile version:
- [ ] Please be mindful of the order in which the sections appear, one way you can accomplish "re-ordering" with CSS is by using flex's property 'order'. You can also do it with Grid, use the one you like the most.
![image](https://user-images.githubusercontent.com/53256139/89627048-e5602e80-d85f-11ea-8359-66f45c3c7f65.png)
- [ ] Please check and fix the differences:
![image](https://user-images.githubusercontent.com/53256139/89628389-d7aba880-d861-11ea-83c0-e2215299fd91.png)
![image](https://user-images.githubusercontent.com/53256139/89628943-a41d4e00-d862-11ea-8aca-06021ab5e408.png)
![image](https://user-images.githubusercontent.com/53256139/89629495-8ac8d180-d863-11ea-9373-5801ccaee118.png)
![image](https://user-images.githubusercontent.com/53256139/89629669-d7aca800-d863-11ea-980f-bd7f317482a8.png)

### Tablet and Desktop version:
- [ ] Notice the layout changes (Hint: You can accomplish this by dividing the section into 2 divs and changing from flex-direction: column in mobile, to flex-direction: row in tablet)
![image](https://user-images.githubusercontent.com/53256139/89630909-a3d28200-d865-11ea-8460-d060cbba08a9.png)

### Desktop version:
- [ ] Please, check and fix the differences:
![image](https://user-images.githubusercontent.com/53256139/89631753-d16bfb00-d866-11ea-8000-27e533d32d3e.png)
- [ ] Notice that the spacing changes, (Hint: you can use responsive margins and paddings from Bootstrap classes)
![image](https://user-images.githubusercontent.com/53256139/89632222-7be41e00-d867-11ea-9d2d-0f28a67fb800.png)

### General requirements

- [ ] Please, be more specific in your commit messages for next time, they are too general. See  [Pathwright lesson on commits](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- [ ] Although you did write a message in your pull request, remember its main purpose is to show a summary of the features you are introducing. Please edit your pull request message and add a short summary of the changes you introduced in this branch as [requested in pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). It is okay to write messages as you did, but the summary should also be there, see a summary example:
![image](https://user-images.githubusercontent.com/53256139/88913714-1e2c5200-d227-11ea-86b8-c57297465ea3.png)

- [ ] Github actions linters are not installed in your repo, please follow the instructions on [this page](https://github.com/microverseinc/linters-config#linters-config) on html-css section to set them up, stickler linter is already deprecated for [Microverse curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/), please remove the stickler files

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-07 09:40 UTC, kitpao commented on README.md
> +[Live Demo Link](https://raw.githack.com/emmanuellekamwa/newsweek/tree/feature-branch)
- [ ] Your live demo link is not working properly, please fix it (remember you should give Githack the link to your .html file): 
![image](https://user-images.githubusercontent.com/53256139/89623319-07ef4900-d85a-11ea-9b50-82f27b07b0cd.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for white text color. 
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for black text color and for margin 0 and padding 0
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +} */
- [x] Please, delete all commented pieces of code
![image](https://user-images.githubusercontent.com/53256139/89626142-8bab3480-d85e-11ea-9895-54e983d26765.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for black background-color
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for white text
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for white text color
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for white text color
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on style.css
> +}
- [x] Try to use bootstrap whenever it is possible, there already exists a bootstrap class for white text color
![image](https://user-images.githubusercontent.com/53256139/89624553-04f55800-d85c-11ea-974c-bef20e20d516.png)

2020-08-07 09:40 UTC, kitpao commented on index.html
> +                <!-- <a href="#" class="big-border pl-3 col"></a> -->
- [x] Please, delete all commented pieces of code
![image](https://user-images.githubusercontent.com/53256139/89626142-8bab3480-d85e-11ea-9895-54e983d26765.png)

2020-08-07 09:40 UTC, kitpao commented on index.html
> +                        </div> -->
- [x] Please, delete all commented pieces of code
![image](https://user-images.githubusercontent.com/53256139/89626142-8bab3480-d85e-11ea-9895-54e983d26765.png)

2020-08-07 09:40 UTC, kitpao commented on index.html
> +                </div> -->
- [x] Please, delete all commented pieces of code
![image](https://user-images.githubusercontent.com/53256139/89626142-8bab3480-d85e-11ea-9895-54e983d26765.png)

2020-08-11 09:38 UTC, emmanuellekamwa commented
HTML and CSS: Working with bootstrap
In this project, I have used bootstrap as much as I could in the following:
 -I have used bootstrap classes for the navbar
 -I have also used it for the body and also for the footer
I still have some issues with my project that I am really stuck with like the navbar. When I try to make it static it misbehaves, the order of some sections are also misbehaving and the "vs" section is not also easy to do. Please can I get some hints on how to approach them? I will be grateful thanks.

2020-08-11 11:02 UTC, kitpao requested changes
# 👋 Hi again @emmanuellekamwa 

I see you did a good job with your pull request message 😄 to make it look more professional you can edit your first comment and add the summary to your initial comment. Also, good work with the positioning of most of your elements 💯 You also did great refactoring your code so you use more bootstrap classes 🌟 

✏️ I have included some tips to help you with the issues you mentioned in the inline comments at the end 🔽 

You also have some pending changes, please check them here:

### All sizes:
- [ ] Don't forget about the labels inside the images of Culture & Travel section
![image](https://user-images.githubusercontent.com/53256139/89887432-e365da80-db93-11ea-89f1-cbf6996c9131.png)

### Mobile version: 
- [ ] Check this border not displaying in mobile:
![image](https://user-images.githubusercontent.com/53256139/89887542-1e680e00-db94-11ea-83cf-79aa439eeff6.png)

* Good job positioning your elements in Magazine section 👏 

- [ ] In your subscribe section, nice job centering your text 🌟  also check and fix the centered position of this image and the text in newsletter section
![image](https://user-images.githubusercontent.com/53256139/89887770-828ad200-db94-11ea-98fe-a67b80105e09.png)

### Tablet and desktop section

- [ ] When you added the "See all features" label, everything moved and it's looking like in the image. You can avoid this problem by putting the "See all features" inside the same div of the cover image
![image](https://user-images.githubusercontent.com/53256139/89888731-072a2000-db96-11ea-87c8-2651916632ed.png)

- [ ] You can use bootstraps or your own media queries to align this part that got different after you fixed the issues in mobile:
![image](https://user-images.githubusercontent.com/53256139/89889080-b5ce6080-db96-11ea-8ce4-cea71fc49c29.png)

### General 

- [ ] Don't forget about your Github actions linters, they are not installed in your repo. Please follow the instructions on [this page](https://github.com/microverseinc/linters-config#linters-config) on html-css section to set them up, stickler linter is already deprecated for [Microverse curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/), please remove the stickler files.

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-11 11:02 UTC, kitpao commented on index.html
> +            >
- [ ] For your fixed navbar, you can use the following code
Styles in `<header class="hidden-nav container-fluid">`
```
    position: fixed;   <!--- put it in the header, not directly in the nav -->
    z-index: 2;          <!--- this is to make it appear on the front of  everything -->
    top: 0;                 <!--- this is to make it stick to the top without margins-->
```
Styles in `<body>`
```
    margin-top: 50px;   <!--- when you put your navbar fixed, your body will go behind it, so you can add a margin to move it down and preserve your spacing -->
```

2020-08-11 11:02 UTC, kitpao commented on index.html
> +                        </article>
- [ ] The reason why you can't order this correctly in mobile, is because your top-story section (the one marked up here) and your "My turn section" are in the same div. And the other section you are trying to accommodate "Featured stories" is in a different div and cannot be put in the middle of another div. You have 2 options:
- Separate top-story section outside of the div so you can call it separately.
OR
- Put everything in the same div, but this option might be messier

2020-08-11 11:02 UTC, kitpao commented on index.html
> +                                    </a>
- [ ] For your VS part, you can [click here to check out this guide for creating shapes](https://css-tricks.com/the-shapes-of-css/) and you can use inside a relative div for the section, absolute positions to align the elements as you wish

2020-08-11 11:02 UTC, kitpao commented on README.md
> +[Live Demo Link](https://raw.githack.com/emmanuellekamwa/newsweek/tree/feature-branch)
- [ ] Your live demo link is not working properly, please fix it (remember you should give Githack the link to your .html file): 
![image](https://user-images.githubusercontent.com/53256139/89623319-07ef4900-d85a-11ea-9b50-82f27b07b0cd.png)

2020-08-13 12:08 UTC, emmanuellekamwa commented
HTML and CSS: working with bootstrap
In this project I have made some changes figured out by the TSE like:
- Making my navbar to be fixed in all screen sizes.
- Re-ordering the sections so that iT should look like the original and for that reason, you will see a part of my code been duplicated inside a commented section. This was to help me reorder everything easily because I couldn't do it with just bootstrap classes.
  I am eager to hear your comments. Tcheers

2020-08-13 19:00 UTC, SafaErden requested changes
## Status: Require changes ♻️ 🚥 

Hi **@emmanuellekamwa**,👋 

your project is awesome 😄 it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find comments below:

**All sizes:**

- [ ] In the original page, 'versus line' is exactly between the two debaters, bur in your page the 'versus line' alignment is broken. Please fix it.
![image](https://user-images.githubusercontent.com/60184961/90173103-9a3ca300-ddac-11ea-98f0-724e1339b366.png)


**Large Size:**

- [ ] Notice that the navbar is fixed when the user scrolls down in the original page, please fix it.
![image](https://user-images.githubusercontent.com/60184961/90172639-fe129c00-ddab-11ea-9e85-c8bd5b8e61ef.png)


**Small Size:**

- [ ] Please consider hiding the sub-header links in mobile view as it is in the original page:
![image](https://user-images.githubusercontent.com/60184961/90173381-0a4b2900-ddad-11ea-8932-72e32a2365e9.png)

- [ ] Please be mindful of the order in which the sections appear, one way you can accomplish "re-ordering" with CSS is by using flex's property 'order'. You can also do it with Grid, use the one you like the most.
![image](https://user-images.githubusercontent.com/60184961/90173618-6746df00-ddad-11ea-87a5-acfaf132af3f.png)

- [ ] Please remember to make you images fill the full width in the sports, culture, tech&science, business,   world, U.S., sections for mobile views:
![image](https://user-images.githubusercontent.com/60184961/90174318-74b09900-ddae-11ea-85b0-8cc98c17b9ac.png)

- [ ] Do not forget to hide the newsletter section image for small-sized screens.
![image](https://user-images.githubusercontent.com/60184961/90174098-1e435a80-ddae-11ea-98c8-4fe65d861f34.png)

- [ ]  Notice that the navbar items get mixed in the small view. I suppose that you try to switch between different navbars for different breakpoints, but it is not working properly. Please fix it.
![image](https://user-images.githubusercontent.com/60184961/90172507-c9064980-ddab-11ea-96f6-53c35de46588.png)

- [ ] The order of the footer links get broken in mobile view. Please fix it.
![image](https://user-images.githubusercontent.com/60184961/90173943-e0463680-ddad-11ea-8913-0696dbbb5955.png)

**README.md**

- [ ] Your live demo link is not working properly, please fix it (remember you should give Githack the link to your .html file):
![image](https://user-images.githubusercontent.com/60184961/90174858-4c756a00-ddaf-11ea-8555-39029f01cc8e.png)

➡️ Please request another review once you are ready 📝

2020-08-14 13:18 UTC, emmanuellekamwa commented
Hi everyone. I have done the necessary modifications pointed out by the TSE but I have a problem with the "vs" part. I want to know how I can arrange it in such a way that it will stay on its position for both small and large screen sizes

2020-08-14 20:08 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

## Hello @emmanuellekamwa :wave: 

## Thank you for working so hard on this project :muscle: you are doing a very good job, keep improving!

## We still have somethings we need to fix, alright? Here are my suggestions:

- [ ] The VS line is still broken on medium and small sizes, you need to fix it. Tip: try playing with media queries, adjusting the values in the `top` and `left` properties you have there.

- [ ] When you fixed your navbar to be sticky, you generated a bug, we can't see the content at the top. Also, on small screens, your navbar links are still showing, not like the original. Check the images below:

## Large
![Screenshot from 2020-08-14 16-50-36](https://user-images.githubusercontent.com/59691171/90287620-95c8c680-de4e-11ea-9b80-9c8f1d2d3654.png)
## Mobile
![Screenshot from 2020-08-14 16-51-05](https://user-images.githubusercontent.com/59691171/90287637-9e210180-de4e-11ea-9e79-70c7068a38ce.png)
<br>

- [ ] In the navbar on mobile width, the content is messed up, check below: 

![Screenshot from 2020-08-14 16-57-15](https://user-images.githubusercontent.com/59691171/90288035-636b9900-de4f-11ea-8d6d-165fe06970f8.png)
<br>

- [ ] In mobile size, your sports, culture, tech&science, business, world, U.S., sections still don't have the full width asked by the previous TSE:

![Screenshot from 2020-08-14 16-58-46](https://user-images.githubusercontent.com/59691171/90288124-97df5500-de4f-11ea-9620-bac0e53c6486.png)
<br>

- [ ] The newsletter image is still there on mobile size:

![Screenshot from 2020-08-14 17-00-41](https://user-images.githubusercontent.com/59691171/90288221-cbba7a80-de4f-11ea-9763-8a083fe483e9.png)

<br>

- [ ] Your live link is still broken, please fix it. Tip: remove `/tree` from the link, and it should work :wink: You just copy your `index.html` file link in Raw Githack and get the 'development' link.

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-17 08:45 UTC, emmanuellekamwa commented
Hi everybody. I have changed the "vs" part of the project and the live demo link but I did not consider the rest of the issues because I don't see them in my code. I have tested in all other browsers that I have like opera and firefox but it is still the same and I can't see any error there

2020-08-17 12:26 UTC, emmanuellekamwa commented
I have now seen the issues and I have fixed them. I hope that my project will get approved this time around

2020-08-17 14:18 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @emmanuellekamwa** 
Good job with your new submission for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [ ] Remember, DRY, group selectors with the same style definition
- [ ] In your "subscribe section" make sure your image doesn't overlap your button. CHeck out the page:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/iVSl4Jll.png) | ![image](https://i.imgur.com/HPgeSuol.png) |

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-17 14:18 UTC, andresporras3423 commented on style.css
> +}
Group selectors with the same style definition.

2020-08-17 14:18 UTC, andresporras3423 commented on style.css
> +}
Group selectors on lines 153 and 171

2020-08-17 14:18 UTC, andresporras3423 commented on style.css
> +}
group selectors on lines 166 and 184

2020-08-18 08:28 UTC, emmanuellekamwa commented
Hi everyone. I think I have fixed all the issues mentioned by the TSE and I hope my project will be approved this time around.

2020-08-18 10:55 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello @emmanuellekamwa** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: :muscle:
Don't forget to merge with the master branch

Keep going like this  :clap: :clap:

Oscar Andrés Russi Porras

2020-08-18 11:11 UTC, merged